import { writeFileSync, readFileSync, readdirSync, copyFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { Manifest } from "./types.js";

const TEMPLATE_DIR = join(dirname(fileURLToPath(import.meta.url)), "templates");

export const SHIM_FILENAME = "safari-compat-shim.js";
export const POLYFILL_FILENAME = "browser-polyfill.min.js";
export const BACKGROUND_PAGE_FILENAME = "background.html";

/**
 * Copy the bundled webextension-polyfill into the staged extension so Chrome code
 * that calls promise-based `browser.*` runs on every browser. The polyfill no-ops
 * when a native `browser` already exists (Safari/Firefox) and otherwise wraps
 * `chrome.*` callbacks as promises. Must load BEFORE the compat shim so the shim's
 * `browser`-namespace patches apply to the polyfilled object. Returns the filename
 * or undefined if the template is unavailable.
 */
export function writePolyfill(targetDir: string): string | undefined {
  const src = join(TEMPLATE_DIR, POLYFILL_FILENAME);
  if (!existsSync(src)) return undefined;
  copyFileSync(src, join(targetDir, POLYFILL_FILENAME));
  return POLYFILL_FILENAME;
}

/**
 * Runtime compatibility shim, prepended to content scripts.
 * Patches the gaps documented in the engineering guide so calls degrade
 * gracefully instead of throwing.
 */
/** Build-time config baked into the shim. All values are derived generically
 *  from the source manifest — nothing extension-specific is hardcoded. */
export interface ShimConfig {
  /** chrome-extension://<id> origin to spoof on proxied requests, or "" if the
   *  source manifest had no `key` to derive an id from. */
  chromeOrigin?: string;
  /** Bare hostnames the extension declares it talks to (host_permissions +
   *  externally_connectable). A cross-origin request to one of these that the
   *  browser blocks (CORS/401/403) is retried through the native host. */
  proxyHosts?: string[];
}

export function shimSource(config: ShimConfig = {}): string {
  // The proxy allowlist + spoofed origin are injected as a JSON literal so the
  // shim needs no string interpolation of untrusted data into code.
  const proxyCfg = JSON.stringify({
    origin: config.chromeOrigin || "",
    hosts: config.proxyHosts || [],
  });
  // String.raw so regex backslash-escapes inside the shim (e.g. /\$(\d+)/,
  // /api\.anthropic\.com/, /^\//) survive verbatim — a plain template literal
  // drops "\." and "\/" to "." and "/", silently corrupting those patterns.
  return String.raw`// safari-compat-shim.js — auto-generated by chrome2safari. Do not edit.
var __C2S_PROXY_CONFIG__ = ${proxyCfg};
(function () {
  "use strict";
  var api = typeof browser !== "undefined" ? browser : (typeof chrome !== "undefined" ? chrome : null);
  if (!api) return;
  var hasChrome = typeof chrome !== "undefined";

  // Inert event stub so module-eval code that reads .addListener on a missing API does not throw.
  function event() {
    return { addListener: function () {}, removeListener: function () {}, hasListener: function () { return false; } };
  }

  // importScripts() in the SW bundle is handled at STAGING time (the imported
  // files are hoisted into background.html as classic <script> tags before the SW
  // module, and the calls are neutralized) — see convertServiceWorkerToBackgroundPage.
  // A runtime polyfill can't help: the default extension CSP is script-src 'self',
  // which forbids eval(), so a fetch+eval importScripts throws EvalError and the SW
  // still aborts before its onConnect listeners register. Defining a no-op here as a
  // belt-and-suspenders guard for any call the staging rewrite missed.
  if (typeof self !== "undefined" && typeof self.importScripts !== "function") {
    try { self.importScripts = function () {}; } catch (e) {}
  }

  // Chrome exposes runtime lifecycle event objects that Safari omits. The SW
  // bundle reads chrome.runtime.<event>.addListener at module-eval; a missing one
  // throws a TypeError that aborts module evaluation BEFORE onMessageExternal is
  // registered (→ OAuth bridge "no external listener captured"). Backfill every
  // standard runtime event as an inert stub if absent. Do NOT touch onMessage /
  // onMessageExternal / onConnect* — those are real (or polyfilled) and carry the
  // OAuth bridge handlers.
  var rtEvents = ["onStartup", "onInstalled", "onSuspend", "onSuspendCanceled",
    "onUpdateAvailable", "onBrowserUpdateAvailable", "onRestartRequired"];
  function backfillRuntimeEvents(rt) {
    if (!rt) return;
    for (var ri = 0; ri < rtEvents.length; ri++) {
      if (!rt[rtEvents[ri]]) { try { rt[rtEvents[ri]] = event(); } catch (e) {} }
    }
  }
  backfillRuntimeEvents(typeof chrome !== "undefined" && chrome.runtime);
  if (typeof browser !== "undefined" && browser !== chrome) backfillRuntimeEvents(browser.runtime);

  // Safari's action popup (default_popup) is a POPOVER, not a side panel sharing
  // the browser window. So tabs.query({active:true,currentWindow:true}) resolves
  // currentWindow to the popover — which has no tabs — and returns []. Code that
  // needs "the active tab" then throws "No active tab" and the chat/agent dies.
  // Wrap tabs.query: if an active-tab query comes back empty, retry against the
  // last-focused normal window, then any active tab. Supports callback + promise.
  function wrapTabsQuery(ns) {
    if (!ns || !ns.tabs || typeof ns.tabs.query !== "function" || ns.tabs.__c2sWrapped) return;
    var _query = ns.tabs.query.bind(ns.tabs);
    function runQuery(q) {
      return new Promise(function (resolve) {
        var settled = false;
        var done = function (r) { if (!settled) { settled = true; resolve(r || []); } };
        try {
          var ret = _query(q, function (r) { done(r); });
          if (ret && typeof ret.then === "function") ret.then(done, function () { done([]); });
        } catch (e) { done([]); }
      });
    }
    ns.tabs.query = function (qi, cb) {
      var wantActive = qi && qi.active;
      var p = runQuery(qi).then(function (res) {
        if (res.length || !wantActive) return res;
        var q2 = Object.assign({}, qi); delete q2.currentWindow; q2.lastFocusedWindow = true;
        return runQuery(q2).then(function (r2) {
          if (r2.length) return r2;
          var q3 = Object.assign({}, qi); delete q3.currentWindow; delete q3.lastFocusedWindow;
          return runQuery(q3);
        });
      });
      if (typeof cb === "function") { p.then(function (r) { cb(r); }, function () { cb([]); }); return; }
      return p;
    };
    ns.tabs.__c2sWrapped = true;
  }
  wrapTabsQuery(typeof chrome !== "undefined" ? chrome : null);
  if (typeof browser !== "undefined" && browser !== chrome) wrapTabsQuery(browser);

  // storage.sync has no iCloud sync in Safari; route it to local so data persists.
  // Only shim when sync is missing or non-functional — never clobber a browser
  // that exposes a real, working storage.sync.
  if (api.storage && api.storage.local &&
      (!api.storage.sync || typeof api.storage.sync.get !== "function")) {
    var local = api.storage.local;
    api.storage.sync = {
      get: function () { return local.get.apply(local, arguments); },
      set: function () { return local.set.apply(local, arguments); },
      remove: function () { return local.remove.apply(local, arguments); },
      clear: function () { return local.clear.apply(local, arguments); },
      getBytesInUse: function () {
        return local.getBytesInUse ? local.getBytesInUse.apply(local, arguments) : Promise.resolve(0);
      },
      // Bundles read storage.sync.onChanged.addListener at module-eval; a stub
      // without it throws and aborts evaluation. storage.onChanged (Chrome's real
      // location — there is no storage.local.onChanged) fires for local writes too.
      onChanged: (api.storage.onChanged) || event(),
    };
  }

  // sidePanel is absent; fall back to opening the panel HTML in a tab. Honor the
  // path the extension actually configured (via setOptions/open) instead of a
  // hardcoded "sidepanel.html" — extensions name the panel page differently
  // (panel.html, side_panel/index.html, …) and a fixed guess 404s on open().
  if (typeof chrome !== "undefined" && !chrome.sidePanel && chrome.tabs) {
    // Seed from the manifest's side_panel.default_path so an extension that relies
    // on the manifest default (never calling setOptions) still opens the right page.
    var panelPath = "sidepanel.html";
    try {
      var mf = chrome.runtime && chrome.runtime.getManifest && chrome.runtime.getManifest();
      if (mf && mf.side_panel && typeof mf.side_panel.default_path === "string" && mf.side_panel.default_path) {
        panelPath = mf.side_panel.default_path;
      }
    } catch (e) {}
    var rememberPath = function (opts) {
      if (opts && typeof opts.path === "string" && opts.path) panelPath = opts.path;
    };
    chrome.sidePanel = {
      open: function (opts) {
        rememberPath(opts);
        return chrome.tabs.create({ url: chrome.runtime.getURL(panelPath) });
      },
      setOptions: function (opts) { rememberPath(opts); return Promise.resolve(); },
      getOptions: function () { return Promise.resolve({ path: panelPath, enabled: true }); },
      setPanelBehavior: function () { return Promise.resolve(); },
      getPanelBehavior: function () { return Promise.resolve({}); },
    };
  }

  // chrome.identity is unsupported; stub so calls reject instead of crashing.
  // Replace with a hosted OAuth2 redirect flow (see SAFARI_NOTES.md).
  if (typeof chrome !== "undefined" && !chrome.identity) {
    var unsupported = function () {
      return Promise.reject(new Error("chrome.identity is unsupported in Safari. Use a hosted OAuth2 flow."));
    };
    chrome.identity = {
      launchWebAuthFlow: unsupported,
      getAuthToken: unsupported,
      removeCachedAuthToken: function (d, cb) { if (cb) cb(); return Promise.resolve(); },
      getRedirectURL: function () { return ""; },
    };
  }

  // chrome.notifications: Safari exposes only a PARTIAL object (create/clear) and
  // omits the event objects (onClicked, onClosed, …). Module-eval that reads
  // chrome.notifications.onClicked.addListener throws and aborts SW registration.
  // Fill BOTH a missing object AND missing members on a partial one.
  if (typeof chrome !== "undefined") {
    var n = chrome.notifications || (chrome.notifications = {});
    if (typeof n.create !== "function") n.create = function (id, opts, cb) {
      // Chrome allows the id to be omitted: create(options, callback). Detect the
      // shifted form (first arg is the options object) and realign.
      if (typeof id === "object" && id !== null) { cb = opts; opts = id; id = ""; }
      try {
        if (typeof Notification !== "undefined" && Notification.permission === "granted" && opts) {
          new Notification(opts.title || "", { body: opts.message || "", icon: opts.iconUrl });
        }
      } catch (e) { /* ignore */ }
      var nid = typeof id === "string" && id ? id : "c2s-" + Date.now();
      // Chrome completes via the callback OR the promise, never both. Match that:
      // return early once the callback path is taken.
      if (typeof cb === "function") { cb(nid); return; }
      return Promise.resolve(nid);
    };
    if (typeof n.clear !== "function") n.clear = function (id, cb) { if (cb) { cb(true); return; } return Promise.resolve(true); };
    if (typeof n.update !== "function") n.update = function (id, opts, cb) { if (cb) { cb(true); return; } return Promise.resolve(true); };
    if (typeof n.getAll !== "function") n.getAll = function (cb) { if (cb) { cb({}); return; } return Promise.resolve({}); };
    if (typeof n.getPermissionLevel !== "function") n.getPermissionLevel = function (cb) { if (cb) { cb("granted"); return; } return Promise.resolve("granted"); };
    if (!n.onClicked) n.onClicked = event();
    if (!n.onClosed) n.onClosed = event();
    if (!n.onButtonClicked) n.onButtonClicked = event();
    if (!n.onShowSettings) n.onShowSettings = event();
    if (!n.onPermissionLevelChanged) n.onPermissionLevelChanged = event();
  }

  // Safari has no native tab-groups API. Chrome's tabGroups is just an
  // association of tab IDs + metadata (title/color/collapsed), so emulate it in
  // memory backed by chrome.tabs. The colored band in the tab bar is UA chrome we
  // can't draw — but the *behavioral* contract (group/ungroup tabs, query groups,
  // get a group's tabs, fire create/update/remove events, expose tab.groupId)
  // works, so grouping logic runs instead of silently no-opping.
  // ponytail: in-memory only — groups don't survive a background-page restart; add
  // chrome.storage.session persistence if a restart drops groups the UI still shows.
  if (hasChrome) {
    var NONE = -1;
    var c2sGroups = Object.create(null); // groupId -> { id,title,color,collapsed,windowId }
    var c2sTabGroup = Object.create(null); // tabId -> groupId
    var c2sNextGid = 1;

    // A real dispatchable event (the shared event() helper is inert).
    var liveEvent = function () {
      var ls = [];
      return {
        addListener: function (f) { if (ls.indexOf(f) < 0) ls.push(f); },
        removeListener: function (f) { var i = ls.indexOf(f); if (i >= 0) ls.splice(i, 1); },
        hasListener: function (f) { return ls.indexOf(f) >= 0; },
        __emit: function () { var a = arguments; for (var i = 0; i < ls.length; i++) { try { ls[i].apply(null, a); } catch (e) {} } },
      };
    };

    if (!chrome.tabGroups) {
      var evCreated = liveEvent(), evUpdated = liveEvent(), evRemoved = liveEvent(), evMoved = liveEvent();
      var tabsOf = function (gid) {
        var ids = []; for (var t in c2sTabGroup) if (c2sTabGroup[t] === gid) ids.push(+t); return ids;
      };
      chrome.tabGroups = {
        TAB_GROUP_ID_NONE: NONE,
        Color: { GREY: "grey", BLUE: "blue", RED: "red", YELLOW: "yellow", GREEN: "green", PINK: "pink", PURPLE: "purple", CYAN: "cyan", ORANGE: "orange" },
        query: function (qi) {
          qi = qi || {};
          var out = [];
          for (var id in c2sGroups) {
            var g = c2sGroups[id];
            if (qi.title != null && g.title !== qi.title) continue;
            if (qi.color != null && g.color !== qi.color) continue;
            if (qi.collapsed != null && !!g.collapsed !== !!qi.collapsed) continue;
            if (qi.windowId != null && qi.windowId >= 0 && g.windowId !== qi.windowId) continue;
            out.push(Object.assign({}, g));
          }
          return Promise.resolve(out);
        },
        get: function (gid) {
          var g = c2sGroups[gid];
          return g ? Promise.resolve(Object.assign({}, g)) : Promise.reject(new Error("No group with id: " + gid));
        },
        update: function (gid, props) {
          var g = c2sGroups[gid];
          if (!g) return Promise.reject(new Error("No group with id: " + gid));
          if (props) for (var k in props) if (k === "title" || k === "color" || k === "collapsed") g[k] = props[k];
          evUpdated.__emit(Object.assign({}, g));
          return Promise.resolve(Object.assign({}, g));
        },
        // Reordering groups within the tab bar isn't expressible in Safari; accept
        // and fire onMoved so callers chaining off it proceed.
        move: function (gid, props) {
          var g = c2sGroups[gid];
          if (!g) return Promise.reject(new Error("No group with id: " + gid));
          evMoved.__emit(Object.assign({}, g));
          return Promise.resolve(Object.assign({}, g));
        },
        onCreated: evCreated, onUpdated: evUpdated, onRemoved: evRemoved, onMoved: evMoved,
        // internal handles for tabs.group/ungroup below
        __reg: c2sGroups, __map: c2sTabGroup, __tabsOf: tabsOf,
      };

      // chrome.tabs.group / ungroup are the create/remove side (absent in Safari).
      if (chrome.tabs && typeof chrome.tabs.group !== "function") {
        chrome.tabs.group = function (opts) {
          opts = opts || {};
          var ids = opts.tabIds == null ? [] : (Array.isArray(opts.tabIds) ? opts.tabIds.slice() : [opts.tabIds]);
          var gid = opts.groupId;
          var created = false;
          if (gid == null || gid === NONE || !c2sGroups[gid]) {
            gid = c2sNextGid++;
            c2sGroups[gid] = { id: gid, title: "", color: "grey", collapsed: false, windowId: opts.createProperties && opts.createProperties.windowId != null ? opts.createProperties.windowId : NONE };
            created = true;
          }
          for (var i = 0; i < ids.length; i++) c2sTabGroup[ids[i]] = gid;
          // Best-effort: pull grouped tabs adjacent. Safari may reject; ignore.
          try { if (ids.length && chrome.tabs.move) chrome.tabs.move(ids, { index: -1 }, function () { void chrome.runtime.lastError; }); } catch (e) {}
          if (created) evCreated.__emit(Object.assign({}, c2sGroups[gid]));
          return Promise.resolve(gid);
        };
        chrome.tabs.ungroup = function (tabIds) {
          var ids = Array.isArray(tabIds) ? tabIds : [tabIds];
          var touched = Object.create(null);
          for (var i = 0; i < ids.length; i++) {
            var g = c2sTabGroup[ids[i]];
            if (g != null) { touched[g] = true; delete c2sTabGroup[ids[i]]; }
          }
          for (var gid in touched) {
            if (tabsOf(+gid).length === 0) { var gone = c2sGroups[gid]; delete c2sGroups[gid]; if (gone) evRemoved.__emit(Object.assign({}, gone)); }
          }
          return Promise.resolve();
        };
      }

      // Expose tab.groupId on tabs.get/query results so reading code sees membership.
      var stampGroup = function (tab) { if (tab && tab.id != null) tab.groupId = c2sTabGroup[tab.id] != null ? c2sTabGroup[tab.id] : NONE; return tab; };
      if (chrome.tabs) {
        ["get", "query"].forEach(function (fn) {
          var orig = chrome.tabs[fn];
          if (typeof orig !== "function" || orig.__c2sGroupStamp) return;
          chrome.tabs[fn] = function () {
            var args = [].slice.call(arguments);
            var cbIdx = args.length - 1;
            var hasCb = typeof args[cbIdx] === "function";
            var wrap = function (res) { Array.isArray(res) ? res.forEach(stampGroup) : stampGroup(res); return res; };
            if (hasCb) { var cb = args[cbIdx]; args[cbIdx] = function (r) { cb(wrap(r)); }; return orig.apply(chrome.tabs, args); }
            var ret = orig.apply(chrome.tabs, args);
            return ret && typeof ret.then === "function" ? ret.then(wrap) : ret;
          };
          chrome.tabs[fn].__c2sGroupStamp = true;
        });
        // Drop a tab from its group when it closes; remove the group when empty.
        if (chrome.tabs.onRemoved && chrome.tabs.onRemoved.addListener) {
          chrome.tabs.onRemoved.addListener(function (tabId) {
            var gid = c2sTabGroup[tabId];
            if (gid == null) return;
            delete c2sTabGroup[tabId];
            if (tabsOf(gid).length === 0) { var gone = c2sGroups[gid]; delete c2sGroups[gid]; if (gone) evRemoved.__emit(Object.assign({}, gone)); }
          });
        }
      }
    }
  }

  // chrome.debugger (CDP) polyfill. Safari has no DevTools Protocol, but
  // Claude-for-Chrome drives pages ENTIRELY through it: attach -> Page.enable ->
  // captureScreenshot -> Input.* -> Runtime.evaluate, plus Page lifecycle events.
  // A reject-stub makes the per-action attach throw, so every agent step (e.g.
  // "Navigate to ...") hangs. Map the subset it uses onto Safari-supported
  // tabs/scripting APIs. Coordinate contract matches CDP: Input.* gets CSS
  // pixels (used as-is for elementFromPoint/clientX); captureScreenshot returns a
  // device-pixel PNG (captureVisibleTab default). The Network domain cannot be
  // reconstructed without CDP -> it no-ops (network request logs unavailable).
  if (hasChrome && !chrome.debugger) {
    var dbgAttached = Object.create(null); // tabId -> true
    var dbgEvtList = [];                    // chrome.debugger.onEvent listeners
    var dbgDetList = [];                    // chrome.debugger.onDetach listeners
    var dbgHooked = false;

    var emitCdp = function (tabId, method, params) {
      var src = { tabId: tabId };
      for (var i = 0; i < dbgEvtList.length; i++) {
        try { dbgEvtList[i](src, method, params || {}); } catch (e) {}
      }
    };

    // Synthesize the Page lifecycle events agent navigation waiters listen for,
    // from chrome.tabs.onUpdated (CDP never fires in Safari).
    var hookLifecycle = function () {
      if (dbgHooked || !chrome.tabs || !chrome.tabs.onUpdated) return;
      dbgHooked = true;
      chrome.tabs.onUpdated.addListener(function (tabId, info, tab) {
        if (!dbgAttached[tabId]) return;
        var fid = String(tabId);
        var url = (tab && tab.url) || info.url || "";
        if (info.status === "loading") {
          emitCdp(tabId, "Page.frameStartedLoading", { frameId: fid });
          emitCdp(tabId, "Page.frameNavigated", { frame: { id: fid, loaderId: fid, url: url } });
        } else if (info.status === "complete") {
          emitCdp(tabId, "Page.loadEventFired", { timestamp: Date.now() / 1000 });
          emitCdp(tabId, "Page.frameStoppedLoading", { frameId: fid });
          emitCdp(tabId, "Page.lifecycleEvent", { frameId: fid, name: "load" });
        }
      });
      // A driven tab closing mid-run is an involuntary detach: Chrome fires
      // onDetach("target_closed"). Without this the agent's onDetach cleanup
      // never runs and waiters can hang on a dead tab.
      if (chrome.tabs.onRemoved && chrome.tabs.onRemoved.addListener) {
        chrome.tabs.onRemoved.addListener(function (tabId) {
          if (!dbgAttached[tabId]) return;
          delete dbgAttached[tabId];
          var src = { tabId: tabId };
          for (var i = 0; i < dbgDetList.length; i++) {
            try { dbgDetList[i](src, "target_closed"); } catch (e) {}
          }
        });
      }
    };

    var mapButton = function (b) { return b === "right" ? 2 : (b === "middle" ? 1 : 0); };

    // --- functions injected into the target tab (must be self-contained) ---
    var pageMouse = function (x, y, type, button, clickCount) {
      var el = document.elementFromPoint(x, y) || document.body;
      if (!el) return false;
      var common = { bubbles: true, cancelable: true, composed: true, view: window,
        clientX: x, clientY: y, button: button, buttons: type === "mousePressed" ? 1 : 0 };
      var fire = function (name, Ctor) {
        try { el.dispatchEvent(new Ctor(name, Object.assign({ pointerId: 1, isPrimary: true, pointerType: "mouse" }, common))); }
        catch (e) { try { el.dispatchEvent(new MouseEvent(name, common)); } catch (e2) {} }
      };
      if (type === "mousePressed") {
        fire("pointerdown", window.PointerEvent || MouseEvent);
        fire("mousedown", MouseEvent);
        if (typeof el.focus === "function") { try { el.focus(); } catch (e) {} }
      } else if (type === "mouseReleased") {
        fire("pointerup", window.PointerEvent || MouseEvent);
        fire("mouseup", MouseEvent);
        try { el.dispatchEvent(new MouseEvent("click", Object.assign({}, common, { detail: clickCount || 1 }))); } catch (e) {}
        if ((clickCount || 1) >= 2) { try { el.dispatchEvent(new MouseEvent("dblclick", common)); } catch (e) {} }
      } else if (type === "mouseMoved") {
        fire("pointermove", window.PointerEvent || MouseEvent);
        fire("mousemove", MouseEvent);
      }
      return true;
    };

    var pageWheel = function (x, y, dx, dy) {
      var el = document.elementFromPoint(x, y) || document.scrollingElement || document.body;
      try { el.dispatchEvent(new WheelEvent("wheel", { bubbles: true, cancelable: true, composed: true, clientX: x, clientY: y, deltaX: dx || 0, deltaY: dy || 0 })); } catch (e) {}
      var sc = document.scrollingElement || document.documentElement;
      if (sc) { sc.scrollLeft += dx || 0; sc.scrollTop += dy || 0; }
      return true;
    };

    var pageKey = function (type, key, code, keyCode, text, modifiers) {
      var target = document.activeElement || document.body;
      var name = type === "keyUp" ? "keyup" : (type === "rawKeyDown" || type === "keyDown" ? "keydown" : null);
      var init = { bubbles: true, cancelable: true, composed: true, key: key || "", code: code || "",
        keyCode: keyCode || 0, which: keyCode || 0,
        altKey: !!(modifiers & 1), ctrlKey: !!(modifiers & 2), metaKey: !!(modifiers & 4), shiftKey: !!(modifiers & 8) };
      if (name && target) { try { target.dispatchEvent(new KeyboardEvent(name, init)); } catch (e) {} }
      if ((type === "char" || type === "keyDown") && text && text.length) {
        var t = document.activeElement;
        if (t && (t.tagName === "INPUT" || t.tagName === "TEXTAREA")) {
          var s = t.selectionStart != null ? t.selectionStart : t.value.length;
          var e2 = t.selectionEnd != null ? t.selectionEnd : t.value.length;
          t.value = t.value.slice(0, s) + text + t.value.slice(e2);
          t.selectionStart = t.selectionEnd = s + text.length;
          try { t.dispatchEvent(new Event("input", { bubbles: true })); } catch (e) {}
        } else if (t && t.isContentEditable) {
          try { document.execCommand("insertText", false, text); } catch (e) {}
          try { t.dispatchEvent(new InputEvent("input", { bubbles: true, data: text })); } catch (e) {}
        }
      }
      return true;
    };

    var pageInsertText = function (text) {
      var t = document.activeElement;
      if (!t) return false;
      if (t.tagName === "INPUT" || t.tagName === "TEXTAREA") {
        var s = t.selectionStart != null ? t.selectionStart : t.value.length;
        var e2 = t.selectionEnd != null ? t.selectionEnd : t.value.length;
        t.value = t.value.slice(0, s) + text + t.value.slice(e2);
        t.selectionStart = t.selectionEnd = s + text.length;
        try { t.dispatchEvent(new Event("input", { bubbles: true })); } catch (e) {}
        return true;
      }
      if (t.isContentEditable) {
        try { document.execCommand("insertText", false, text); } catch (e) {}
        try { t.dispatchEvent(new InputEvent("input", { bubbles: true, data: text })); } catch (e) {}
        return true;
      }
      return false;
    };

    var inject = function (tabId, fn, args, world) {
      if (!chrome.scripting || !chrome.scripting.executeScript || tabId == null) return Promise.resolve(undefined);
      var opts = { target: { tabId: tabId }, func: fn, args: args };
      if (world) opts.world = world;
      return chrome.scripting.executeScript(opts).then(
        function (r) { return (r && r[0]) ? r[0].result : undefined; },
        function () { return undefined; }
      );
    };

    var screenshot = function (tabId, params) {
      params = params || {};
      var opts = { format: params.format === "jpeg" ? "jpeg" : "png" };
      if (opts.format === "jpeg" && params.quality != null) opts.quality = params.quality;
      var capture = function (windowId) {
        return new Promise(function (resolve, reject) {
          try {
            chrome.tabs.captureVisibleTab(windowId, opts, function (dataUrl) {
              if (chrome.runtime.lastError || !dataUrl) { reject(new Error(chrome.runtime.lastError ? chrome.runtime.lastError.message : "captureVisibleTab failed")); return; }
              var d = String(dataUrl); var ci = d.indexOf(",");
              resolve({ data: ci >= 0 ? d.slice(ci + 1) : d });
            });
          } catch (e) { reject(e); }
        });
      };
      return new Promise(function (resolve, reject) {
        try {
          chrome.tabs.get(tabId, function (tab) {
            if (chrome.runtime.lastError || !tab) { capture().then(resolve, reject); return; }
            capture(tab.windowId).then(resolve, reject);
          });
        } catch (e) { capture().then(resolve, reject); }
      });
    };

    var evaluate = function (tabId, params) {
      params = params || {};
      // CDP Runtime.evaluate runs in the page's MAIN world; inject there so the
      // expression sees the page's JS globals (the isolated world shares the DOM
      // but not page window properties, which would silently yield undefined).
      return inject(tabId, function (code) {
        try { return { ok: true, value: (0, eval)(code) }; }
        catch (e) { return { ok: false, error: String((e && e.message) || e) }; }
      }, [params.expression || ""], "MAIN").then(function (res) {
        if (res && res.ok) return { result: { type: typeof res.value, value: res.value } };
        return { result: { type: "undefined" }, exceptionDetails: { text: (res && res.error) || "evaluate failed" } };
      });
    };

    var runCommand = function (target, method, params) {
      var tabId = target && target.tabId;
      params = params || {};
      switch (method) {
        case "Page.captureScreenshot": return screenshot(tabId, params);
        case "Runtime.evaluate": return evaluate(tabId, params);
        case "Input.dispatchMouseEvent":
          if (params.type === "mouseWheel") return inject(tabId, pageWheel, [params.x || 0, params.y || 0, params.deltaX || 0, params.deltaY || 0]).then(function () { return {}; });
          return inject(tabId, pageMouse, [params.x || 0, params.y || 0, params.type, mapButton(params.button), params.clickCount || 1]).then(function () { return {}; });
        case "Input.dispatchKeyEvent":
          return inject(tabId, pageKey, [params.type, params.key, params.code, params.windowsVirtualKeyCode || params.nativeVirtualKeyCode || 0, params.text, params.modifiers || 0]).then(function () { return {}; });
        case "Input.insertText":
          return inject(tabId, pageInsertText, [params.text || ""]).then(function () { return {}; });
        default:
          // Page.enable/disable, Runtime.enable, Network.*, *.handleJavaScriptDialog,
          // Emulation.*, DOM.* and any unknown command -> resolve so the loop proceeds.
          return Promise.resolve({});
      }
    };

    var withCb = function (promise, cb) {
      if (typeof cb === "function") { promise.then(function (r) { try { cb(r); } catch (e) {} }, function () { try { cb(); } catch (e) {} }); return; }
      return promise;
    };

    chrome.debugger = {
      attach: function (target, version, cb) {
        if (target && target.tabId != null) dbgAttached[target.tabId] = true;
        hookLifecycle();
        return withCb(Promise.resolve(), cb);
      },
      detach: function (target, cb) {
        if (target && target.tabId != null) delete dbgAttached[target.tabId];
        return withCb(Promise.resolve(), cb);
      },
      sendCommand: function (target, method, params, cb) {
        if (typeof params === "function") { cb = params; params = {}; }
        return withCb(runCommand(target, method, params).catch(function () { return {}; }), cb);
      },
      getTargets: function (cb) {
        var list = Object.keys(dbgAttached).map(function (id) { return { tabId: Number(id), attached: true, type: "page" }; });
        return withCb(Promise.resolve(list), cb);
      },
      onEvent: {
        addListener: function (fn) { if (typeof fn === "function") dbgEvtList.push(fn); },
        removeListener: function (fn) { var i = dbgEvtList.indexOf(fn); if (i >= 0) dbgEvtList.splice(i, 1); },
        hasListener: function (fn) { return dbgEvtList.indexOf(fn) >= 0; },
      },
      onDetach: {
        addListener: function (fn) { if (typeof fn === "function") dbgDetList.push(fn); },
        removeListener: function (fn) { var i = dbgDetList.indexOf(fn); if (i >= 0) dbgDetList.splice(i, 1); },
        hasListener: function (fn) { return dbgDetList.indexOf(fn) >= 0; },
      },
    };
  }

  // offscreen documents do not exist in Safari; stub so createDocument/hasDocument resolve.
  if (hasChrome && !chrome.offscreen) {
    chrome.offscreen = {
      Reason: { AUDIO_PLAYBACK: "AUDIO_PLAYBACK", BLOBS: "BLOBS", CLIPBOARD: "CLIPBOARD", DOM_PARSER: "DOM_PARSER", DOM_SCRAPING: "DOM_SCRAPING", IFRAME_SCRIPTING: "IFRAME_SCRIPTING", TESTING: "TESTING", USER_MEDIA: "USER_MEDIA", WORKERS: "WORKERS", DISPLAY_MEDIA: "DISPLAY_MEDIA", GEOLOCATION: "GEOLOCATION", LOCAL_STORAGE: "LOCAL_STORAGE", BATTERY_STATUS: "BATTERY_STATUS", MATCH_MEDIA: "MATCH_MEDIA", WEB_RTC: "WEB_RTC" },
      createDocument: function () { return Promise.resolve(); },
      closeDocument: function () { return Promise.resolve(); },
      hasDocument: function () { return Promise.resolve(false); },
    };
  }

  // Namespaces with NO Safari equivalent that Chrome extensions still reference at
  // module-eval (reading <ns>.<event>.addListener or an enum) throw a TypeError that
  // aborts SW/page evaluation and blanks the surface — same failure class as
  // tabGroups/notifications above. Backfill each absent namespace with inert stubs:
  // event objects no-op, methods resolve/reject so callers degrade instead of crash.
  if (hasChrome) {
    var rejectUnsupported = function (name) {
      return function () { return Promise.reject(new Error(name + " is unsupported in Safari.")); };
    };
    var resolveEmpty = function (val) {
      return function () { return Promise.resolve(val); };
    };
    // Fill members the host omitted WITHOUT clobbering ones it provides. Safari may
    // expose a PARTIAL namespace (e.g. chrome.system with only .cpu), so a blanket
    // "if (!chrome.X)" guard would skip backfill and let chrome.X.missing.foo throw.
    var fill = function (obj, members) {
      if (!obj) return;
      for (var k in members) { if (!obj[k]) { try { obj[k] = members[k]; } catch (e) {} } }
    };
    // A ChromeSetting leaf (chrome.privacy.*, chrome.contentSettings.*): get/set/clear + event.
    var chromeSetting = function () {
      return { get: resolveEmpty({ value: undefined, levelOfControl: "not_controllable" }), set: resolveEmpty(undefined), clear: resolveEmpty(undefined), onChange: event() };
    };

    // chrome.omnibox — no address-bar keyword surface. Listeners never fire.
    chrome.omnibox = chrome.omnibox || {};
    fill(chrome.omnibox, {
      setDefaultSuggestion: function () {},
      onInputStarted: event(), onInputChanged: event(),
      onInputEntered: event(), onInputCancelled: event(), onDeleteSuggestion: event(),
    });

    // chrome.tts — route callers to Web Speech API when present, else no-op.
    chrome.tts = chrome.tts || {};
    fill(chrome.tts, {
      speak: function (text, opts, cb) {
        if (typeof opts === "function") { cb = opts; opts = {}; }
        try {
          if (typeof speechSynthesis !== "undefined" && text) {
            var u = new SpeechSynthesisUtterance(String(text));
            if (opts) { if (opts.rate) u.rate = opts.rate; if (opts.pitch) u.pitch = opts.pitch; if (opts.volume != null) u.volume = opts.volume; if (opts.lang) u.lang = opts.lang; }
            speechSynthesis.speak(u);
          }
        } catch (e) {}
        if (typeof cb === "function") { cb(); return; }
        return Promise.resolve();
      },
      stop: function () { try { if (typeof speechSynthesis !== "undefined") speechSynthesis.cancel(); } catch (e) {} },
      pause: function () { try { if (typeof speechSynthesis !== "undefined") speechSynthesis.pause(); } catch (e) {} },
      resume: function () { try { if (typeof speechSynthesis !== "undefined") speechSynthesis.resume(); } catch (e) {} },
      isSpeaking: function (cb) { var s = (typeof speechSynthesis !== "undefined") && speechSynthesis.speaking; if (typeof cb === "function") { cb(s); return; } return Promise.resolve(s); },
      getVoices: resolveEmpty([]),
      onEvent: event(),
    });

    // chrome.proxy — settings object so .set()/.get() and .onProxyError don't throw.
    chrome.proxy = chrome.proxy || {};
    fill(chrome.proxy, { settings: chromeSetting(), onProxyError: event() });

    // chrome.power — keepAwake/releaseKeepAwake are fire-and-forget no-ops.
    chrome.power = chrome.power || {};
    fill(chrome.power, { requestKeepAwake: function () {}, releaseKeepAwake: function () {}, reportActivity: function (cb) { if (cb) cb(); } });

    // chrome.system.* — each sub-namespace returns empty info. Backfill per
    // sub-namespace so a partial host (e.g. only chrome.system.cpu) is completed.
    chrome.system = chrome.system || {};
    fill(chrome.system, {
      cpu: { getInfo: resolveEmpty({ numOfProcessors: 0, archName: "", modelName: "", features: [], processors: [] }) },
      memory: { getInfo: resolveEmpty({ capacity: 0, availableCapacity: 0 }) },
      storage: { getInfo: resolveEmpty([]), onAttached: event(), onDetached: event() },
      display: { getInfo: resolveEmpty([]), onDisplayChanged: event() },
    });

    // chrome.management — only self-introspection is plausibly needed; stub the rest.
    chrome.management = chrome.management || {};
    fill(chrome.management, {
      getSelf: function (cb) {
        var info = { id: (chrome.runtime && chrome.runtime.id) || "", enabled: true, installType: "normal", name: "", version: "" };
        if (typeof cb === "function") { cb(info); return; }
        return Promise.resolve(info);
      },
      getAll: resolveEmpty([]), get: rejectUnsupported("management.get"),
      getPermissionWarningsById: resolveEmpty([]), getPermissionWarningsByManifest: resolveEmpty([]),
      setEnabled: rejectUnsupported("management.setEnabled"), uninstallSelf: resolveEmpty(undefined),
      onInstalled: event(), onUninstalled: event(), onEnabled: event(), onDisabled: event(),
    });

    // Settings-style read/write APIs with no Safari surface. Each leaf is a full
    // ChromeSetting so chrome.privacy.network.<x>.get()/.set() never throw.
    chrome.privacy = chrome.privacy || {};
    fill(chrome.privacy, { network: {}, services: {}, websites: {} });
    fill(chrome.privacy.network, { networkPredictionEnabled: chromeSetting(), webRTCIPHandlingPolicy: chromeSetting() });
    fill(chrome.privacy.services, { autofillAddressEnabled: chromeSetting(), autofillCreditCardEnabled: chromeSetting(), passwordSavingEnabled: chromeSetting(), safeBrowsingEnabled: chromeSetting() });
    fill(chrome.privacy.websites, { thirdPartyCookiesAllowed: chromeSetting(), referrersEnabled: chromeSetting(), hyperlinkAuditingEnabled: chromeSetting(), doNotTrackEnabled: chromeSetting() });
    chrome.contentSettings = chrome.contentSettings || {};
    fill(chrome.contentSettings, {
      cookies: chromeSetting(), images: chromeSetting(), javascript: chromeSetting(), location: chromeSetting(),
      notifications: chromeSetting(), popups: chromeSetting(), camera: chromeSetting(), microphone: chromeSetting(),
    });
    chrome.browsingData = chrome.browsingData || {};
    fill(chrome.browsingData, { remove: resolveEmpty(undefined), settings: resolveEmpty({ options: {}, dataToRemove: {}, dataRemovalPermitted: {} }) });

    // Capture APIs → defer to getDisplayMedia where possible, else reject.
    chrome.tabCapture = chrome.tabCapture || {};
    fill(chrome.tabCapture, { capture: rejectUnsupported("tabCapture"), getCapturedTabs: resolveEmpty([]), onStatusChanged: event() });
    chrome.desktopCapture = chrome.desktopCapture || {};
    // chooseDesktopMedia MUST invoke its callback (Chrome calls it with "" on cancel);
    // returning only a request id leaves callers waiting forever. Signal cancellation.
    fill(chrome.desktopCapture, {
      chooseDesktopMedia: function (sources, targetTab, cb) {
        if (typeof targetTab === "function") cb = targetTab;
        if (typeof cb === "function") { try { cb(""); } catch (e) {} }
        return -1;
      },
      cancelChooseDesktopMedia: function () {},
    });
    chrome.pageCapture = chrome.pageCapture || {};
    fill(chrome.pageCapture, { saveAsMHTML: rejectUnsupported("pageCapture") });

    // chrome.readingList — native Reading List has no JS API.
    chrome.readingList = chrome.readingList || {};
    fill(chrome.readingList, {
      addEntry: rejectUnsupported("readingList.addEntry"), removeEntry: rejectUnsupported("readingList.removeEntry"),
      updateEntry: rejectUnsupported("readingList.updateEntry"), query: resolveEmpty([]),
      onEntryAdded: event(), onEntryRemoved: event(), onEntryUpdated: event(),
    });

    // dual(value, cb): honor Chrome's callback form AND return a promise otherwise.
    var dual = function (value, cb) {
      if (typeof cb === "function") { try { cb(value); } catch (e) {} return; }
      return Promise.resolve(value);
    };

    // MV2 aliases: browserAction/pageAction code running on an MV3/Safari manifest.
    // Point both at chrome.action so setBadgeText/setIcon/onClicked keep working.
    if (chrome.action) {
      if (!chrome.browserAction) chrome.browserAction = chrome.action;
      if (!chrome.pageAction) {
        chrome.pageAction = Object.assign(Object.create(chrome.action), {
          show: function (tabId, cb) { return dual(undefined, cb); },
          hide: function (tabId, cb) { return dual(undefined, cb); },
        });
      }
    }

    // chrome.extension (MV2 legacy surface).
    chrome.extension = chrome.extension || {};
    fill(chrome.extension, {
      getURL: function (p) { return chrome.runtime && chrome.runtime.getURL ? chrome.runtime.getURL(p) : p; },
      getViews: function () { return []; },
      getBackgroundPage: function () { return null; },
      isAllowedIncognitoAccess: function (cb) { return dual(false, cb); },
      isAllowedFileSchemeAccess: function (cb) { return dual(false, cb); },
      inIncognitoContext: false,
      onRequest: event(), onRequestExternal: event(),
    });

    // chrome.alarms — Safari has it, but temp-loaded/background-page contexts can
    // omit it. Full polyfill on setTimeout: one-shot + periodic, name registry.
    if (!chrome.alarms) {
      var alarmReg = Object.create(null);
      var alarmList = [];
      var alarmInfo = function (a) { return { name: a.name, scheduledTime: a.when, periodInMinutes: a.period || undefined }; };
      var armAlarm = function (a) {
        a.t = setTimeout(function () {
          if (a.period) { a.when = Date.now() + a.period * 60000; armAlarm(a); }
          else delete alarmReg[a.name];
          for (var i = 0; i < alarmList.length; i++) { try { alarmList[i](alarmInfo(a)); } catch (e) {} }
        }, Math.max(0, a.when - Date.now()));
      };
      chrome.alarms = {
        create: function (name, info, cb) {
          if (typeof name === "object") { cb = info; info = name; name = ""; }
          if (typeof info === "function") { cb = info; info = undefined; }
          info = info || {};
          var when = info.when != null ? info.when : Date.now() + (info.delayInMinutes != null ? info.delayInMinutes : (info.periodInMinutes || 0)) * 60000;
          var prev = alarmReg[name]; if (prev) clearTimeout(prev.t);
          armAlarm(alarmReg[name] = { name: name, when: when, period: info.periodInMinutes || null });
          return dual(undefined, cb);
        },
        get: function (name, cb) { var a = alarmReg[name || ""]; return dual(a ? alarmInfo(a) : undefined, cb); },
        getAll: function (cb) { var out = []; for (var k in alarmReg) out.push(alarmInfo(alarmReg[k])); return dual(out, cb); },
        clear: function (name, cb) { var a = alarmReg[name || ""]; if (a) { clearTimeout(a.t); delete alarmReg[name || ""]; } return dual(!!a, cb); },
        clearAll: function (cb) { var any = false; for (var k in alarmReg) { clearTimeout(alarmReg[k].t); delete alarmReg[k]; any = true; } return dual(any, cb); },
        onAlarm: {
          addListener: function (fn) { if (typeof fn === "function") alarmList.push(fn); },
          removeListener: function (fn) { var i = alarmList.indexOf(fn); if (i >= 0) alarmList.splice(i, 1); },
          hasListener: function (fn) { return alarmList.indexOf(fn) >= 0; },
        },
      };
    }

    // storage.session (Safari < 16.4 lacks it) — in-memory map, correct get() key
    // semantics (string | array | object-with-defaults | null = everything).
    if (chrome.storage && !chrome.storage.session) {
      var sessMem = Object.create(null);
      var sessGet = function (keys) {
        var out = {};
        if (keys == null) { for (var k in sessMem) out[k] = sessMem[k]; return out; }
        if (typeof keys === "string") keys = [keys];
        if (Array.isArray(keys)) { for (var i = 0; i < keys.length; i++) { if (keys[i] in sessMem) out[keys[i]] = sessMem[keys[i]]; } return out; }
        for (var d in keys) out[d] = (d in sessMem) ? sessMem[d] : keys[d];
        return out;
      };
      chrome.storage.session = {
        get: function (keys, cb) { if (typeof keys === "function") { cb = keys; keys = null; } return dual(sessGet(keys), cb); },
        set: function (items, cb) { for (var k in items) sessMem[k] = items[k]; return dual(undefined, cb); },
        remove: function (keys, cb) { if (typeof keys === "string") keys = [keys]; if (Array.isArray(keys)) { for (var i = 0; i < keys.length; i++) delete sessMem[keys[i]]; } return dual(undefined, cb); },
        clear: function (cb) { sessMem = Object.create(null); return dual(undefined, cb); },
        getBytesInUse: function (k, cb) { if (typeof k === "function") { cb = k; } return dual(0, cb); },
        setAccessLevel: function (o, cb) { return dual(undefined, cb); },
        onChanged: event(),
      };
    }
    // storage.managed — no MDM-policy surface; reads come back empty.
    if (chrome.storage && !chrome.storage.managed) {
      chrome.storage.managed = {
        get: function (keys, cb) { if (typeof keys === "function") { cb = keys; } return dual({}, cb); },
        getBytesInUse: function (k, cb) { if (typeof k === "function") { cb = k; } return dual(0, cb); },
        onChanged: event(),
      };
    }

    // chrome.idle — derive state from page visibility where a document exists;
    // a background context simply reports "active".
    chrome.idle = chrome.idle || {};
    fill(chrome.idle, {
      queryState: function (sec, cb) {
        var state = (typeof document !== "undefined" && document.visibilityState === "hidden") ? "idle" : "active";
        return dual(state, cb);
      },
      setDetectionInterval: function () {},
      getAutoLockDelay: function (cb) { return dual(0, cb); },
      onStateChanged: event(),
    });

    // chrome.downloads — no Safari API. Creative fallback: navigate a tab to the
    // URL so WebKit's downloader takes over (or click an <a download> when a DOM
    // exists). Enough for "save this file" flows; queries return empty.
    chrome.downloads = chrome.downloads || {};
    fill(chrome.downloads, {
      download: function (opts, cb) {
        var url = (opts && opts.url) || "";
        var id = Date.now() % 2147483647;
        try {
          if (typeof document !== "undefined" && document.body) {
            var a = document.createElement("a");
            a.href = url; if (opts && opts.filename) a.download = opts.filename;
            document.body.appendChild(a); a.click(); a.remove();
          } else if (chrome.tabs && chrome.tabs.create) {
            chrome.tabs.create({ url: url, active: false });
          }
        } catch (e) {}
        return dual(id, cb);
      },
      search: function (q, cb) { return dual([], cb); },
      cancel: function (id, cb) { return dual(undefined, cb); },
      pause: function (id, cb) { return dual(undefined, cb); },
      resume: function (id, cb) { return dual(undefined, cb); },
      erase: function (q, cb) { return dual([], cb); },
      open: rejectUnsupported("downloads.open"), show: function () {}, showDefaultFolder: function () {},
      getFileIcon: function (id, o, cb) { if (typeof o === "function") { cb = o; } return dual("", cb); },
      setUiOptions: function (o, cb) { return dual(undefined, cb); },
      onCreated: event(), onChanged: event(), onErased: event(), onDeterminingFilename: event(),
    });

    // chrome.search — no Safari surface; open the query in a search-engine tab.
    chrome.search = chrome.search || {};
    fill(chrome.search, {
      query: function (opts, cb) {
        var text = (opts && opts.text) || "";
        var url = "https://www.google.com/search?q=" + encodeURIComponent(text);
        try {
          if (chrome.tabs && chrome.tabs.create) {
            if (opts && opts.disposition === "CURRENT_TAB" && chrome.tabs.update) chrome.tabs.update({ url: url });
            else chrome.tabs.create({ url: url });
          }
        } catch (e) {}
        return dual(undefined, cb);
      },
      Disposition: { CURRENT_TAB: "CURRENT_TAB", NEW_TAB: "NEW_TAB", NEW_WINDOW: "NEW_WINDOW" },
    });

    // chrome.history — Safari gates it behind extra entitlements; complete the
    // missing members so feature-detection degrades instead of crashing.
    chrome.history = chrome.history || {};
    fill(chrome.history, {
      search: function (q, cb) { return dual([], cb); },
      getVisits: function (d, cb) { return dual([], cb); },
      addUrl: function (d, cb) { return dual(undefined, cb); },
      deleteUrl: function (d, cb) { return dual(undefined, cb); },
      deleteRange: function (d, cb) { return dual(undefined, cb); },
      deleteAll: function (cb) { return dual(undefined, cb); },
      onVisited: event(), onVisitRemoved: event(),
    });

    // chrome.bookmarks — same: partial/gated. Reads return an empty tree.
    chrome.bookmarks = chrome.bookmarks || {};
    fill(chrome.bookmarks, {
      getTree: function (cb) { return dual([{ id: "0", title: "", children: [] }], cb); },
      get: function (ids, cb) { return dual([], cb); },
      getChildren: function (id, cb) { return dual([], cb); },
      getRecent: function (n, cb) { return dual([], cb); },
      getSubTree: function (id, cb) { return dual([], cb); },
      search: function (q, cb) { return dual([], cb); },
      create: rejectUnsupported("bookmarks.create"), move: rejectUnsupported("bookmarks.move"),
      update: rejectUnsupported("bookmarks.update"), remove: rejectUnsupported("bookmarks.remove"),
      removeTree: rejectUnsupported("bookmarks.removeTree"),
      onCreated: event(), onRemoved: event(), onChanged: event(), onMoved: event(),
      onChildrenReordered: event(), onImportBegan: event(), onImportEnded: event(),
    });

    // chrome.sessions / chrome.topSites — no Safari surface; empty reads.
    chrome.sessions = chrome.sessions || {};
    fill(chrome.sessions, {
      MAX_SESSION_RESULTS: 25,
      getRecentlyClosed: function (f, cb) { if (typeof f === "function") { cb = f; } return dual([], cb); },
      getDevices: function (f, cb) { if (typeof f === "function") { cb = f; } return dual([], cb); },
      restore: rejectUnsupported("sessions.restore"),
      onChanged: event(),
    });
    chrome.topSites = chrome.topSites || {};
    fill(chrome.topSites, { get: function (cb) { return dual([], cb); } });

    // chrome.commands — Safari wires manifest shortcuts itself; complete the JS side.
    chrome.commands = chrome.commands || {};
    fill(chrome.commands, {
      getAll: function (cb) { return dual([], cb); },
      onCommand: event(),
    });

    // chrome.contextMenus — supported on macOS, absent on iOS. Complete missing
    // members so cross-platform code registers without crashing.
    chrome.contextMenus = chrome.contextMenus || {};
    fill(chrome.contextMenus, {
      ContextType: { ALL: "all", PAGE: "page", SELECTION: "selection", LINK: "link", IMAGE: "image", VIDEO: "video", AUDIO: "audio", FRAME: "frame", EDITABLE: "editable", ACTION: "action" },
      ItemType: { NORMAL: "normal", CHECKBOX: "checkbox", RADIO: "radio", SEPARATOR: "separator" },
      create: function (props, cb) { if (typeof cb === "function") { try { cb(); } catch (e) {} } return (props && props.id) || Date.now(); },
      update: function (id, props, cb) { return dual(undefined, cb); },
      remove: function (id, cb) { return dual(undefined, cb); },
      removeAll: function (cb) { return dual(undefined, cb); },
      onClicked: event(),
    });

    // chrome.webNavigation — Safari ships a subset; backfill the events Chrome
    // bundles read at module-eval plus frame queries.
    chrome.webNavigation = chrome.webNavigation || {};
    fill(chrome.webNavigation, {
      getFrame: function (d, cb) { return dual(null, cb); },
      getAllFrames: function (d, cb) { return dual([], cb); },
      onBeforeNavigate: event(), onCommitted: event(), onDOMContentLoaded: event(),
      onCompleted: event(), onErrorOccurred: event(), onCreatedNavigationTarget: event(),
      onReferenceFragmentUpdated: event(), onTabReplaced: event(), onHistoryStateUpdated: event(),
    });

    // chrome.windows — Safari ships most of it on macOS but OMITS some events
    // (notably onBoundsChanged) and is absent entirely on iOS. A bundle reading
    // chrome.windows.onBoundsChanged.addListener at module-eval throws and aborts
    // evaluation (same class as tabGroups/notifications). Backfill only the missing
    // members so native create/update/get/remove keep working untouched. Where the
    // whole namespace is absent (iOS), the method stubs degrade to tabs/no-ops.
    chrome.windows = chrome.windows || {};
    fill(chrome.windows, {
      WINDOW_ID_NONE: -1, WINDOW_ID_CURRENT: -2,
      CreateType: { NORMAL: "normal", POPUP: "popup", PANEL: "panel" },
      WindowState: { NORMAL: "normal", MINIMIZED: "minimized", MAXIMIZED: "maximized", FULLSCREEN: "fullscreen", LOCKED_FULLSCREEN: "locked-fullscreen" },
      // Fallbacks only reached when Safari omits the method (iOS); on macOS the
      // native impl is present so fill() skips these. create→open a tab.
      get: function (id, info, cb) { if (typeof info === "function") { cb = info; } return dual(null, cb); },
      getCurrent: function (info, cb) { if (typeof info === "function") { cb = info; } return dual(null, cb); },
      getLastFocused: function (info, cb) { if (typeof info === "function") { cb = info; } return dual(null, cb); },
      getAll: function (info, cb) { if (typeof info === "function") { cb = info; } return dual([], cb); },
      create: function (opts, cb) {
        var url = opts && opts.url;
        try { if (url && chrome.tabs && chrome.tabs.create) chrome.tabs.create({ url: Array.isArray(url) ? url[0] : url }); } catch (e) {}
        return dual({ id: -1, tabs: [] }, cb);
      },
      update: function (id, info, cb) { return dual({ id: id }, cb); },
      remove: function (id, cb) { return dual(undefined, cb); },
      onCreated: event(), onRemoved: event(), onFocusChanged: event(), onBoundsChanged: event(),
    });

    // chrome.devtools — DevTools-page extensions (devtools_page in the manifest)
    // have NO Safari equivalent; the panels/network/inspectedWindow surface is
    // absent, so a devtools.html bundle reading chrome.devtools.network.onRequestFinished
    // throws on load. Backfill inert stubs so the devtools page loads without
    // crashing (panels simply never appear — there is no Safari host for them).
    chrome.devtools = chrome.devtools || {};
    fill(chrome.devtools, {
      inspectedWindow: {
        tabId: -1,
        eval: function (expr, opts, cb) { if (typeof opts === "function") { cb = opts; } return dual(undefined, cb); },
        getResources: function (cb) { return dual([], cb); },
        reload: function () {},
        onResourceAdded: event(), onResourceContentCommitted: event(),
      },
      network: {
        getHAR: function (cb) { return dual({ entries: [] }, cb); },
        onRequestFinished: event(), onNavigated: event(),
      },
      panels: {
        themeName: "default", elements: { onSelectionChanged: event() }, sources: { onSelectionChanged: event() },
        create: function (title, icon, page, cb) { if (typeof cb === "function") { try { cb({ onShown: event(), onHidden: event(), onSearch: event() }); } catch (e) {} } },
        setOpenResourceHandler: function () {}, openResource: function (url, line, cb) { if (typeof cb === "function") cb(); },
        onThemeChanged: event(),
      },
    });

    // chrome.app — legacy hosted-app probe; bundles read chrome.app.isInstalled
    // and chrome.app.getDetails() to detect a companion app. Report "no app".
    chrome.app = chrome.app || {};
    fill(chrome.app, {
      isInstalled: false,
      getDetails: function () { return null; },
      getIsInstalled: function () { return false; },
      installState: function (cb) { if (typeof cb === "function") { cb("not_installed"); return; } return Promise.resolve("not_installed"); },
      runningState: function () { return "cannot_run"; },
    });

    // chrome.cookies — present in Safari but without onChanged; empty fallbacks.
    chrome.cookies = chrome.cookies || {};
    fill(chrome.cookies, {
      get: function (d, cb) { return dual(null, cb); },
      getAll: function (d, cb) { return dual([], cb); },
      set: function (d, cb) { return dual(null, cb); },
      remove: function (d, cb) { return dual(null, cb); },
      getAllCookieStores: function (cb) { return dual([{ id: "0", tabIds: [] }], cb); },
      onChanged: event(),
    });

    // chrome.permissions — answer "not granted" rather than throw, so callers
    // take their no-permission code path.
    chrome.permissions = chrome.permissions || {};
    fill(chrome.permissions, {
      contains: function (p, cb) { return dual(false, cb); },
      getAll: function (cb) { return dual({ permissions: [], origins: [] }, cb); },
      request: function (p, cb) { return dual(false, cb); },
      remove: function (p, cb) { return dual(false, cb); },
      onAdded: event(), onRemoved: event(),
    });

    // chrome.webRequest — observation-only in Safari (macOS); backfill the event
    // objects + handler behavior constant so listener registration never throws.
    chrome.webRequest = chrome.webRequest || {};
    fill(chrome.webRequest, {
      MAX_HANDLER_BEHAVIOR_CHANGED_CALLS_PER_10_MINUTES: 20,
      handlerBehaviorChanged: function (cb) { return dual(undefined, cb); },
      onBeforeRequest: event(), onBeforeSendHeaders: event(), onSendHeaders: event(),
      onHeadersReceived: event(), onAuthRequired: event(), onResponseStarted: event(),
      onBeforeRedirect: event(), onCompleted: event(), onErrorOccurred: event(),
      onActionIgnored: event(),
    });

    // chrome.declarativeContent — bundles construct matchers at module-eval
    // (new chrome.declarativeContent.PageStateMatcher(...)); rules never fire.
    if (!chrome.declarativeContent) {
      var DCtor = function (o) { Object.assign(this, o || {}); };
      chrome.declarativeContent = {
        PageStateMatcher: DCtor, ShowAction: DCtor, ShowPageAction: DCtor, SetIcon: DCtor,
        RequestContentScript: DCtor,
        onPageChanged: {
          addRules: function (r, cb) { return dual([], cb); },
          removeRules: function (ids, cb) { return dual(undefined, cb); },
          getRules: function (ids, cb) { if (typeof ids === "function") { cb = ids; } return dual([], cb); },
        },
      };
    }

    // chrome.gcm / chrome.instanceID — Chrome push plumbing; registration rejects
    // so callers fall back to their polling path.
    chrome.gcm = chrome.gcm || {};
    fill(chrome.gcm, {
      MAX_MESSAGE_SIZE: 4096,
      register: rejectUnsupported("gcm.register"), unregister: rejectUnsupported("gcm.unregister"),
      send: rejectUnsupported("gcm.send"),
      onMessage: event(), onMessagesDeleted: event(), onSendError: event(),
    });
    chrome.instanceID = chrome.instanceID || {};
    fill(chrome.instanceID, {
      getID: rejectUnsupported("instanceID.getID"), getCreationTime: rejectUnsupported("instanceID.getCreationTime"),
      getToken: rejectUnsupported("instanceID.getToken"), deleteToken: rejectUnsupported("instanceID.deleteToken"),
      deleteID: rejectUnsupported("instanceID.deleteID"),
      onTokenRefresh: event(),
    });

    // chrome.fontSettings / accessibilityFeatures — ChromeSetting-style leaves.
    chrome.fontSettings = chrome.fontSettings || {};
    fill(chrome.fontSettings, {
      getFontList: function (cb) { return dual([], cb); },
      getFont: function (d, cb) { return dual({ fontId: "", levelOfControl: "not_controllable" }, cb); },
      setFont: function (d, cb) { return dual(undefined, cb); },
      clearFont: function (d, cb) { return dual(undefined, cb); },
      getDefaultFontSize: function (d, cb) { if (typeof d === "function") { cb = d; } return dual({ pixelSize: 16, levelOfControl: "not_controllable" }, cb); },
      setDefaultFontSize: function (d, cb) { return dual(undefined, cb); },
      onFontChanged: event(), onDefaultFontSizeChanged: event(), onDefaultFixedFontSizeChanged: event(), onMinimumFontSizeChanged: event(),
    });
    chrome.accessibilityFeatures = chrome.accessibilityFeatures || {};
    fill(chrome.accessibilityFeatures, {
      spokenFeedback: chromeSetting(), largeCursor: chromeSetting(), stickyKeys: chromeSetting(),
      highContrast: chromeSetting(), screenMagnifier: chromeSetting(), autoclick: chromeSetting(),
      virtualKeyboard: chromeSetting(), caretHighlight: chromeSetting(), cursorHighlight: chromeSetting(),
      animationPolicy: chromeSetting(),
    });

    // chrome.ttsEngine / userScripts / dom — fill remaining dev-facing surfaces.
    chrome.ttsEngine = chrome.ttsEngine || {};
    fill(chrome.ttsEngine, {
      updateVoices: function () {},
      onSpeak: event(), onStop: event(), onPause: event(), onResume: event(),
    });
    chrome.userScripts = chrome.userScripts || {};
    fill(chrome.userScripts, {
      register: rejectUnsupported("userScripts.register"), unregister: function (f, cb) { return dual(undefined, cb); },
      update: rejectUnsupported("userScripts.update"),
      getScripts: function (f, cb) { if (typeof f === "function") { cb = f; } return dual([], cb); },
      configureWorld: function (p, cb) { return dual(undefined, cb); },
    });
    chrome.dom = chrome.dom || {};
    fill(chrome.dom, {
      openOrClosedShadowRoot: function (el) { return (el && el.shadowRoot) || null; },
    });

    // chrome.i18n — Safari supports getMessage/getUILanguage but NOT detectLanguage,
    // and some contexts omit getAcceptLanguages. Code that reads
    // chrome.i18n.detectLanguage(...).then() throws (detectLanguage is undefined),
    // so backfill the missing members without clobbering Safari's real getMessage.
    chrome.i18n = chrome.i18n || {};
    fill(chrome.i18n, {
      getMessage: function (key, subs) {
        // Last-resort only — used when Safari omits the native impl. Returns the
        // key so the UI shows something rather than "undefined".
        var s = Array.isArray(subs) ? subs : (subs != null ? [subs] : []);
        return String(key == null ? "" : key).replace(/\$(\d+)/g, function (_, d) { return s[d - 1] != null ? s[d - 1] : ""; });
      },
      getUILanguage: function () {
        try { return (navigator && (navigator.language || (navigator.languages && navigator.languages[0]))) || "en"; }
        catch (e) { return "en"; }
      },
      getAcceptLanguages: function (cb) {
        var langs;
        try { langs = (navigator && navigator.languages && navigator.languages.slice()) || ["en"]; }
        catch (e) { langs = ["en"]; }
        return dual(langs, cb);
      },
      // Safari has no language-detection engine; report "und" (undetermined) at 100%
      // so callers get a well-formed result object instead of a thrown TypeError.
      detectLanguage: function (text, cb) {
        var res = { isReliable: false, languages: [{ language: "und", percentage: 100 }] };
        return dual(res, cb);
      },
    });

    // ChromeOS / enterprise / kiosk tail — every remaining chrome.* namespace gets
    // an inert object so feature probes and module-eval reads can't crash.
    var inertNamespaces = {
      fileBrowserHandler: { onExecute: event() },
      fileSystemProvider: {
        mount: rejectUnsupported("fileSystemProvider.mount"), unmount: rejectUnsupported("fileSystemProvider.unmount"),
        getAll: function (cb) { return dual([], cb); }, get: rejectUnsupported("fileSystemProvider.get"),
        onUnmountRequested: event(), onGetMetadataRequested: event(), onReadDirectoryRequested: event(),
        onOpenFileRequested: event(), onCloseFileRequested: event(), onReadFileRequested: event(),
      },
      documentScan: { scan: rejectUnsupported("documentScan.scan") },
      printerProvider: { onGetPrintersRequested: event(), onGetCapabilityRequested: event(), onPrintRequested: event(), onGetUsbPrinterInfoRequested: event() },
      printing: {
        submitJob: rejectUnsupported("printing.submitJob"), cancelJob: rejectUnsupported("printing.cancelJob"),
        getPrinters: function (cb) { return dual([], cb); }, getPrinterInfo: rejectUnsupported("printing.getPrinterInfo"),
        onJobStatusChanged: event(),
      },
      printingMetrics: { getPrintJobs: function (cb) { return dual([], cb); }, onPrintJobFinished: event() },
      certificateProvider: {
        requestPin: rejectUnsupported("certificateProvider.requestPin"), stopPinRequest: rejectUnsupported("certificateProvider.stopPinRequest"),
        setCertificates: rejectUnsupported("certificateProvider.setCertificates"), reportSignature: rejectUnsupported("certificateProvider.reportSignature"),
        onCertificatesUpdateRequested: event(), onSignatureRequested: event(),
      },
      vpnProvider: {
        createConfig: rejectUnsupported("vpnProvider.createConfig"), destroyConfig: rejectUnsupported("vpnProvider.destroyConfig"),
        setParameters: rejectUnsupported("vpnProvider.setParameters"), sendPacket: rejectUnsupported("vpnProvider.sendPacket"),
        notifyConnectionStateChanged: rejectUnsupported("vpnProvider.notifyConnectionStateChanged"),
        onPlatformMessage: event(), onPacketReceived: event(), onConfigRemoved: event(), onConfigCreated: event(), onUIEvent: event(),
      },
      wallpaper: { setWallpaper: rejectUnsupported("wallpaper.setWallpaper") },
      loginState: {
        getProfileType: function (cb) { return dual("USER_PROFILE", cb); },
        getSessionState: function (cb) { return dual("IN_SESSION", cb); },
        onSessionStateChanged: event(),
      },
      loginScreenStorage: {
        storePersistentData: rejectUnsupported("loginScreenStorage.storePersistentData"),
        retrievePersistentData: rejectUnsupported("loginScreenStorage.retrievePersistentData"),
        storeCredentials: rejectUnsupported("loginScreenStorage.storeCredentials"),
        retrieveCredentials: rejectUnsupported("loginScreenStorage.retrieveCredentials"),
      },
      signedInDevices: { get: function (d, cb) { if (typeof d === "function") { cb = d; } return dual([], cb); }, onDeviceInfoChange: event() },
      processes: {
        getProcessInfo: rejectUnsupported("processes.getProcessInfo"), terminate: rejectUnsupported("processes.terminate"),
        getProcessIdForTab: rejectUnsupported("processes.getProcessIdForTab"),
        onUpdated: event(), onUpdatedWithMemory: event(), onCreated: event(), onExited: event(),
      },
      webAuthenticationProxy: {
        attach: rejectUnsupported("webAuthenticationProxy.attach"), detach: rejectUnsupported("webAuthenticationProxy.detach"),
        completeCreateRequest: rejectUnsupported("webAuthenticationProxy.completeCreateRequest"),
        completeGetRequest: rejectUnsupported("webAuthenticationProxy.completeGetRequest"),
        completeIsUvpaaRequest: rejectUnsupported("webAuthenticationProxy.completeIsUvpaaRequest"),
        onCreateRequest: event(), onGetRequest: event(), onIsUvpaaRequest: event(), onRequestCanceled: event(),
      },
      platformKeys: {
        selectClientCertificates: rejectUnsupported("platformKeys.selectClientCertificates"),
        getKeyPair: rejectUnsupported("platformKeys.getKeyPair"), getKeyPairBySpki: rejectUnsupported("platformKeys.getKeyPairBySpki"),
        subtleCrypto: function () { return (typeof crypto !== "undefined" && crypto.subtle) || null; },
        verifyTLSServerCertificate: rejectUnsupported("platformKeys.verifyTLSServerCertificate"),
      },
    };
    for (var nsName in inertNamespaces) {
      chrome[nsName] = chrome[nsName] || {};
      fill(chrome[nsName], inertNamespaces[nsName]);
    }
    chrome.enterprise = chrome.enterprise || {};
    fill(chrome.enterprise, {
      platformKeys: {
        getTokens: function (cb) { return dual([], cb); },
        getCertificates: function (t, cb) { return dual([], cb); },
        importCertificate: rejectUnsupported("enterprise.platformKeys.importCertificate"),
        removeCertificate: rejectUnsupported("enterprise.platformKeys.removeCertificate"),
        challengeKey: rejectUnsupported("enterprise.platformKeys.challengeKey"),
      },
      deviceAttributes: {
        getDirectoryDeviceId: function (cb) { return dual("", cb); },
        getDeviceSerialNumber: function (cb) { return dual("", cb); },
        getDeviceAssetId: function (cb) { return dual("", cb); },
        getDeviceAnnotatedLocation: function (cb) { return dual("", cb); },
        getDeviceHostname: function (cb) { return dual("", cb); },
      },
      hardwarePlatform: { getHardwarePlatformInfo: function (cb) { return dual({ manufacturer: "", model: "" }, cb); } },
      networkingAttributes: { getNetworkDetails: rejectUnsupported("enterprise.networkingAttributes.getNetworkDetails") },
    });

    // chrome.runtime stragglers.
    if (chrome.runtime) {
      fill(chrome.runtime, {
        requestUpdateCheck: function (cb) { return dual({ status: "no_update" }, cb); },
        setUninstallURL: function (u, cb) { return dual(undefined, cb); },
        openOptionsPage: function (cb) {
          try {
            var m = chrome.runtime.getManifest ? chrome.runtime.getManifest() : null;
            var page = m && (m.options_page || (m.options_ui && m.options_ui.page));
            if (page && chrome.tabs && chrome.tabs.create) chrome.tabs.create({ url: chrome.runtime.getURL(page) });
          } catch (e) {}
          return dual(undefined, cb);
        },
      });
    }
  }

  // Safari (current WebKit) CRASHES THE WHOLE BROWSER when a declarativeNetRequest
  // ruleset contains a "modifyHeaders" action: reading the rule back from its SQLite
  // store null-derefs in WebExtensionContext::loadDeclarativeNetRequestRules ->
  // getRulesWithRuleIDs (EXC_BAD_ACCESS at 0x24). The Claude service worker registers
  // a modifyHeaders SESSION rule to pin Origin for api.anthropic.com — which Safari
  // ignores anyway (Origin is browser-controlled) and which the fetch/XHR header patch
  // below already covers. Strip modifyHeaders rules out of update{Session,Dynamic}Rules
  // so the crash never arms; block/redirect/allow rules pass through untouched.
  if (hasChrome && chrome.declarativeNetRequest) {
    var dnrNs = chrome.declarativeNetRequest;
    var stripModifyHeaders = function (opts) {
      if (!opts || !Array.isArray(opts.addRules)) return opts;
      var safe = opts.addRules.filter(function (r) {
        return !(r && r.action && r.action.type === "modifyHeaders");
      });
      return safe.length === opts.addRules.length ? opts : Object.assign({}, opts, { addRules: safe });
    };
    var wrapDnrUpdate = function (name) {
      var orig = dnrNs[name];
      if (typeof orig !== "function" || orig.__c2sWrapped) return;
      dnrNs[name] = function (opts, cb) {
        try { opts = stripModifyHeaders(opts); } catch (e) {}
        return orig.call(dnrNs, opts, cb);
      };
      dnrNs[name].__c2sWrapped = true;
    };
    wrapDnrUpdate("updateSessionRules");
    wrapDnrUpdate("updateDynamicRules");
  }

  // api.anthropic.com requires the "anthropic-dangerous-direct-browser-access"
  // header on every browser-origin request; the SDK adds it to /v1/messages but
  // some hand-written fetches (e.g. /api/oauth/account/settings) omit it, giving
  // 401 "CORS requests must set 'anthropic-dangerous-direct-browser-access'
  // header". This header IS settable from JS, so inject it here (covers fetch+XHR).
  // The Origin header is NOT settable in-browser (JS can't, and a DNR modifyHeaders
  // rule crashes Safari) — when a backend rejects the Safari origin anyway, the
  // native-messaging proxy below retries the request out-of-process.
  (function () {
    var ANTH = /(^|[/.])api\.anthropic\.com(?=[/:?]|$)/i;
    var HDR = "anthropic-dangerous-direct-browser-access";
    var g = (typeof self !== "undefined") ? self : (typeof window !== "undefined" ? window : null);

    // ---- native-messaging proxy --------------------------------------------
    // Safari sets the request Origin to safari-web-extension://<uuid>, which an
    // extension's backend may reject (e.g. an org CORS allowlist keyed on the
    // Chrome origin). Origin/sec-fetch-* are forbidden headers JS cannot set, and
    // a DNR modifyHeaders rule crashes Safari — so the ONLY way to send the Chrome
    // origin is out-of-process. When a request to a declared backend host is
    // blocked in-browser (network error / 401 / 403), retry it through the Swift
    // host (browser.runtime.sendNativeMessage), which fetches it server-side with
    // the spoofed Origin and no CORS. Hosts + origin are derived from the manifest
    // at build time; nothing here is extension-specific.
    var PCFG = (typeof __C2S_PROXY_CONFIG__ !== "undefined") ? __C2S_PROXY_CONFIG__ : { origin: "", hosts: [] };
    var proxyHosts = (PCFG && PCFG.hosts) || [];
    // sendNativeMessage is a background-context privilege; in a page/sidepanel it
    // is usually absent. So this context can proxy if EITHER it can talk to the
    // native host directly OR it can reach the SW (which forwards to the host).
    var directNative = !!(api && api.runtime && typeof api.runtime.sendNativeMessage === "function");
    var canMessageSW = !!(api && api.runtime && typeof api.runtime.sendMessage === "function");
    var isBackground = directNative; // SW/background page is where sendNativeMessage lives
    var proxyEnabled = proxyHosts.length > 0 && (directNative || canMessageSW);
    function shouldProxy(url) {
      if (!proxyEnabled) return false;
      var host;
      try { host = new URL(url, (typeof location !== "undefined" ? location.href : undefined)).hostname; }
      catch (e) { return false; }
      for (var i = 0; i < proxyHosts.length; i++) {
        var ph = proxyHosts[i];
        if (host === ph || (host.length > ph.length && host.slice(-(ph.length + 1)) === "." + ph)) return true;
      }
      return false;
    }
    function headersToObj(h) {
      var o = {};
      // Forbidden request headers the browser would have set itself; replaying
      // them server-side is wrong or ignored. Cookie is intentionally dropped —
      // the native host attaches the shared cookie jar; a stale JS-visible Cookie
      // value (httpOnly cookies aren't even here) would only mislead it.
      var forbidden = { "host": 1, "cookie": 1, "content-length": 1, "connection": 1,
                        "origin": 1, "referer": 1 };
      try { if (h && typeof h.forEach === "function") h.forEach(function (v, k) {
        if (!forbidden[String(k).toLowerCase()]) o[k] = v;
      }); } catch (e) {}
      return o;
    }
    // Send the proxy request to the native host. From the background context, go
    // direct; otherwise relay through the SW via runtime.sendMessage and let it
    // call the host (it has the privilege + the authenticated cookie context).
    function sendToHost(msg) {
      if (directNative) {
        // Safari ignores the app-id arg and returns a Promise; Chrome wants a cb.
        var p = api.runtime.sendNativeMessage("application.id", msg);
        if (p && typeof p.then === "function") return p;
        return new Promise(function (resolve, reject) {
          try { api.runtime.sendNativeMessage("application.id", msg, function (r) {
            var err = api.runtime.lastError;
            if (err) reject(new Error(err.message || "native host error")); else resolve(r);
          }); } catch (e) { reject(e); }
        });
      }
      // Relay through the SW. The SW installs a {__c2sProxyRelay} handler (below).
      var rp = api.runtime.sendMessage({ __c2sProxyRelay: true, req: msg });
      if (rp && typeof rp.then === "function") return rp;
      return new Promise(function (resolve, reject) {
        try { api.runtime.sendMessage({ __c2sProxyRelay: true, req: msg }, function (r) {
          var err = api.runtime.lastError;
          if (err) reject(new Error(err.message || "SW relay error")); else resolve(r);
        }); } catch (e) { reject(e); }
      });
    }
    // Resolve to a real Response built from the host's reply, or reject so the
    // caller sees a normal failure. Body is base64 to survive JSON transport.
    function proxyFetch(url, method, headers, body) {
      // Forward JS-visible cookies so the host can authenticate the request.
      // httpOnly cookies are invisible here and cannot be carried — see the Swift
      // handler's note. Only sent from a document context (SW has no document).
      var cookie = "";
      try { if (typeof document !== "undefined" && document.cookie) cookie = document.cookie; } catch (e) {}
      var msg = { __c2sProxy: true, url: url, method: method || "GET", headers: headers || {}, body: body || null, cookie: cookie };
      return sendToHost(msg).then(function (r) {
        if (!r || r.error) throw new Error((r && r.error) || "native host: empty reply");
        var bytes = null;
        try { if (typeof r.bodyB64 === "string") { var bin = atob(r.bodyB64); bytes = new Uint8Array(bin.length); for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i); } } catch (e) {}
        return new Response(bytes, { status: r.status || 200, statusText: r.statusText || "", headers: r.headers || {} });
      });
    }

    // SW side: handle proxy-relay messages from page/sidepanel contexts and
    // forward them to the native host. Only registered in the background context.
    if (isBackground && api.runtime && api.runtime.onMessage && proxyHosts.length > 0) {
      api.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
        if (!msg || msg.__c2sProxyRelay !== true || !msg.req) return;
        sendToHost(msg.req).then(function (r) { sendResponse(r); },
                                 function (e) { sendResponse({ error: String((e && e.message) || e) }); });
        return true; // async response
      });
    }

    if (g && typeof g.fetch === "function" && !g.fetch.__c2sPatched) {
      var _fetch = g.fetch;
      g.fetch = function (input, init) {
        var url = "";
        try {
          url = typeof input === "string" ? input : (input && input.url) || "";
          if (ANTH.test(url)) {
            var base = init || {};
            var srcH = base.headers || (typeof input !== "string" && input && input.headers) || {};
            var h = new Headers(srcH);
            if (!h.has(HDR)) h.set(HDR, "true");
            init = Object.assign({}, base, { headers: h });
          }
        } catch (e) { /* fall through with original args */ }
        var self_ = this;
        var attempt = _fetch.call(self_, input, init);
        var willProxy = shouldProxy(url);
        try { console.log("[c2s] fetch", url, "proxyEnabled=" + proxyEnabled, "willProxy=" + willProxy, "ctx=" + (isBackground ? "bg" : "page")); } catch (e) {}
        if (!willProxy) return attempt;
        // Capture request shape once for a possible proxy retry.
        var reqMethod = (init && init.method) || (typeof input !== "string" && input && input.method) || "GET";
        var reqHeaders = headersToObj(init && init.headers ? new Headers(init.headers) : null);
        var reqBody = (init && typeof init.body === "string") ? init.body : null;
        var viaProxy = function () {
          try { console.log("[c2s] PROXY retry ->", url); } catch (e) {}
          return proxyFetch(url, reqMethod, reqHeaders, reqBody).then(
            function (r) { try { console.log("[c2s] PROXY result", url, "status=" + r.status); } catch (e) {} return r; },
            function (err) { try { console.error("[c2s] PROXY failed", url, String((err && err.message) || err)); } catch (e) {} throw err; }
          );
        };
        // A blocked cross-origin request surfaces as a rejected fetch (TypeError),
        // which is the real "Origin rejected" signal. A 401/403 is ALSO retried
        // once, since some gates answer with a status rather than a hard block.
        return attempt.then(
          function (resp) {
            try { console.log("[c2s] fetch resolved", url, "status=" + (resp && resp.status)); } catch (e) {}
            return (resp && (resp.status === 401 || resp.status === 403)) ? viaProxy().catch(function () { return resp; }) : resp;
          },
          function (netErr) { try { console.log("[c2s] fetch rejected", url, String((netErr && netErr.message) || netErr)); } catch (e) {} return viaProxy().catch(function () { throw netErr; }); }
        );
      };
      g.fetch.__c2sPatched = true;
    }
    if (typeof XMLHttpRequest !== "undefined" && !XMLHttpRequest.prototype.__c2sPatched) {
      var _open = XMLHttpRequest.prototype.open;
      var _send = XMLHttpRequest.prototype.send;
      XMLHttpRequest.prototype.open = function (m, u) {
        try { this.__c2sAnthropic = ANTH.test(String(u)); } catch (e) {}
        return _open.apply(this, arguments);
      };
      XMLHttpRequest.prototype.send = function () {
        try { if (this.__c2sAnthropic) this.setRequestHeader(HDR, "true"); } catch (e) {}
        return _send.apply(this, arguments);
      };
      XMLHttpRequest.prototype.__c2sPatched = true;
    }
  })();

  // Safari: the action popup (sidepanel.html) opens as a POPOVER with no
  // ?tabId=<id> query param (Chrome injects one) and not mode=window. A side
  // panel that reads new URLSearchParams(location.search).get("tabId") to learn
  // which browser tab to drive then gets null, leaving it with no active tab.
  // Resolve the active tab now (tabs.query is already wrapped to fall back to the
  // last-focused normal window) and make get("tabId") return it when the param is
  // missing. Runs in the side-panel/popup document — detected by the conventional
  // "sidepanel" filename OR by matching the manifest's configured side_panel /
  // action popup page, so a panel named panel.html (etc.) is still covered.
  var c2sIsPanelDoc = function () {
    if (typeof location === "undefined") return false;
    var path = (location.pathname || "").replace(/^\//, "").toLowerCase();
    if (/sidepanel/i.test(path)) return true;
    try {
      var m = (typeof chrome !== "undefined" && chrome.runtime && chrome.runtime.getManifest)
        ? chrome.runtime.getManifest() : null;
      if (!m) return false;
      var act = m.action || m.browser_action || {};
      var pages = [m.side_panel && m.side_panel.default_path, act.default_popup];
      for (var i = 0; i < pages.length; i++) {
        if (typeof pages[i] === "string" && pages[i].replace(/^\//, "").toLowerCase() === path) return true;
      }
    } catch (e) {}
    return false;
  };
  if (typeof window !== "undefined" && typeof location !== "undefined" && c2sIsPanelDoc()) {
    try {
      var hasParam = !!new URLSearchParams(location.search).get("tabId");
      if (!hasParam) {
        var c2sTabId = null;
        var qns = (typeof chrome !== "undefined" && chrome.tabs) ? chrome.tabs : (api && api.tabs);
        var assign = function (r) {
          if (c2sTabId == null && r && r[0] && r[0].id != null) {
            c2sTabId = String(r[0].id);
            try {
              var u = new URL(location.href); u.searchParams.set("tabId", c2sTabId);
              history.replaceState(history.state, "", u.toString());
            } catch (e) {}
          }
        };
        if (qns && qns.query) {
          try {
            var qret = qns.query({ active: true, currentWindow: true }, assign);
            if (qret && typeof qret.then === "function") qret.then(assign);
          } catch (e) {}
        }
        var _uspGet = URLSearchParams.prototype.get;
        URLSearchParams.prototype.get = function (k) {
          var val = _uspGet.call(this, k);
          if (val == null && k === "tabId" && c2sTabId != null) return c2sTabId;
          return val;
        };
      }
    } catch (e) { /* ignore */ }
  }
})();
`;
}

export function writeShim(targetDir: string, config: ShimConfig = {}): string {
  const p = join(targetDir, SHIM_FILENAME);
  writeFileSync(p, shimSource(config), "utf-8");
  return SHIM_FILENAME;
}

/** Hostnames the extension declares it talks to: host_permissions +
 *  externally_connectable.matches. These are the backends that may reject the
 *  Safari origin and therefore need native-host proxying. Generic — derived
 *  purely from the manifest. */
export function deriveProxyHosts(manifest: Manifest): string[] {
  const patterns: string[] = [];
  if (Array.isArray(manifest.host_permissions)) patterns.push(...manifest.host_permissions);
  const ec = manifest.externally_connectable;
  if (ec && Array.isArray(ec.matches)) patterns.push(...ec.matches);
  // CSP connect-src is where API endpoints are declared when host_permissions is
  // a broad wildcard (<all_urls>). These https/wss origins are the real backends.
  const csp = manifest.content_security_policy;
  const cspStr = typeof csp === "string" ? csp : csp?.extension_pages ?? "";
  const connect = /(?:^|;)\s*connect-src\s+([^;]+)/i.exec(cspStr);
  if (connect) {
    for (const tok of connect[1].split(/\s+/)) {
      if (/^(https?|wss?):\/\//i.test(tok)) patterns.push(tok);
    }
  }
  const hosts = new Set<string>();
  for (const pat of patterns) {
    if (typeof pat !== "string") continue;
    // Match patterns / CSP sources: "*://*.example.com/*", "https://api.foo.com/*",
    // "wss://api.foo.com". Strip scheme, leading "*.", port, and any path.
    const m = /^[^:]+:\/\/([^/]+)/.exec(pat);
    if (!m) continue;
    const host = m[1].replace(/^\*\./, "").replace(/:\d+$/, "");
    // Skip wildcard-only hosts (<all_urls>, "*") — too broad to proxy safely.
    if (!host || host === "*" || host.includes("*")) continue;
    hosts.add(host.toLowerCase());
  }
  return [...hosts];
}

function walkHtmlFiles(dir: string, acc: string[] = []): string[] {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const entry of entries) {
    const name = entry.name;
    if (name === "node_modules" || name === ".git" || name.startsWith("__MACOSX")) continue;
    const full = join(dir, name);
    if (entry.isDirectory()) walkHtmlFiles(full, acc);
    else if (entry.isFile() && name.toLowerCase().endsWith(".html")) acc.push(full);
  }
  return acc;
}

/**
 * Inject the polyfill (optional) + shim as the first <head> scripts of every
 * extension HTML page (recursively — options/sidepanel pages often live in
 * subdirs). The tags use root-absolute src so they resolve from any depth.
 * Module scripts are deferred, so classic scripts placed in <head> run first —
 * the polyfill defines `browser`, then the shim patches missing chrome / browser
 * namespaces, all before bundle module-eval.
 */
export function injectShimIntoHtmlPages(dir: string, polyfillFile?: string): number {
  const shimTag = `<script src="/${SHIM_FILENAME}"></script>`;
  const polyTag = polyfillFile ? `<script src="/${polyfillFile}"></script>` : "";
  let count = 0;
  for (const file of walkHtmlFiles(dir)) {
    let html = readFileSync(file, "utf-8");
    // Insert only the missing tag(s) so a partial prior injection (either tag)
    // never produces duplicates. Polyfill stays before the shim.
    const missing = [polyTag, shimTag].filter((t) => t && !html.includes(t));
    if (missing.length === 0) continue;
    const toInsert = missing.join("\n    ");
    const headMatch = html.match(/<head[^>]*>/i);
    if (headMatch) {
      const at = headMatch.index! + headMatch[0].length;
      html = html.slice(0, at) + "\n    " + toInsert + html.slice(at);
    } else {
      html = toInsert + "\n" + html;
    }
    writeFileSync(file, html, "utf-8");
    count++;
  }
  return count;
}

/**
 * Side-panel/full-height pages wired as a Safari action popup collapse to a tiny
 * window because they carry no intrinsic size. Inject a sizing style so the popup
 * opens at usable dimensions. style-src allows 'unsafe-inline' in typical MV3 CSPs.
 */
export function injectPopupSizing(dir: string, popupFile: string): void {
  const file = join(dir, popupFile);
  let html: string;
  try {
    html = readFileSync(file, "utf-8");
  } catch {
    return;
  }
  const marker = "c2s-popup-size";
  if (html.includes(marker)) return;
  // color-scheme lets Safari paint the popup canvas in the OS theme *before* the
  // app's CSS/JS boots — without it the popover flashes light even in dark mode.
  //
  // Sizing must survive the app's OWN stylesheet, which loads AFTER this <style>
  // and often sets html/body rules (e.g. Tampermonkey's `body{margin:auto}` would
  // otherwise win the cascade and offset the popover). So:
  //  - !important on the structural props so a later equal-specificity app rule
  //    can't override them (margin:auto offset, a stray width/height, etc.).
  //  - Don't hard-pin height. A fixed 600px gives a huge half-empty popover for a
  //    short command menu, and a popup whose body is empty at load and grown by JS
  //    (Tampermonkey's action menu) gets clipped inside a fixed box. Instead let
  //    height fit content (min-height floor for the empty-at-load case, max-height
  //    cap so it never exceeds Safari's popover ceiling and scrolls past it).
  //  - Width keeps a min floor (empty-at-load popups have no intrinsic width) but
  //    grows to content up to a cap, so wide menus aren't squeezed to 400px.
  const style = `<style id="${marker}">:root{color-scheme:light dark;}` +
    `html{margin:0!important;}` +
    `body{margin:0!important;min-width:360px!important;width:max-content!important;max-width:780px!important;` +
    `min-height:200px!important;max-height:600px!important;height:auto!important;` +
    `box-sizing:border-box!important;overflow:auto!important;}</style>`;
  const headMatch = html.match(/<head[^>]*>/i);
  if (headMatch) {
    const at = headMatch.index! + headMatch[0].length;
    html = html.slice(0, at) + "\n    " + style + html.slice(at);
  } else {
    html = style + "\n" + html;
  }
  writeFileSync(file, html, "utf-8");
}

/**
 * Safari starts module service workers unreliably for temp-loaded extensions —
 * the SW often never runs, so anything probing it (e.g. the OAuth content-script
 * bridge) times out with "background not running/reachable". Convert the MV3
 * service worker into a non-persistent background page that loads the compat shim
 * first (so missing chrome.* events are backfilled before the bundle module-evals
 * and aborts) then the SW loader as a module. Mutates `manifest`. No-op when there
 * is no service_worker. Must run AFTER the OAuth bridge so the loader already
 * imports its polyfill.
 */
export function convertServiceWorkerToBackgroundPage(dir: string, manifest: Manifest, polyfillFile?: string): boolean {
  const sw = manifest.background?.service_worker;
  if (!sw) return false;
  const polyTag = polyfillFile && existsSync(join(dir, polyfillFile)) ? `<script src="${polyfillFile}"></script>\n` : "";
  // --no-shim conversions have no shim file; don't reference a missing script.
  const shimTag = existsSync(join(dir, SHIM_FILENAME)) ? `<script src="${SHIM_FILENAME}"></script>\n` : "";

  // importScripts() is undefined in a module background page, so the first call
  // throws and aborts SW evaluation BEFORE its onConnect/onMessage listeners
  // register (→ popup's runtime.connect() gets "No onConnect listeners found").
  // The default extension CSP is script-src 'self' (no eval), so a runtime
  // fetch+eval polyfill can't substitute. Instead hoist each importScripts target
  // into background.html as a classic <script> BEFORE the SW module (the imported
  // files are self-contained IIFEs that just need to run in global scope first —
  // exactly what a prior <script> tag gives), then neutralize the calls in the SW
  // so the now-undefined global is never invoked. CSP-safe and generic.
  const importTags = hoistImportScripts(dir, sw);

  const html = `<!DOCTYPE html>
<meta charset="utf-8">
<title>${manifest.name ?? "Extension"} background</title>
${polyTag}${shimTag}${importTags}<script type="module" src="${sw}"></script>
`;
  writeFileSync(join(dir, BACKGROUND_PAGE_FILENAME), html, "utf-8");
  // MV3 (Safari) rejects persistent background: "A manifest_version >= 3 must be non-persistent."
  manifest.background = { page: BACKGROUND_PAGE_FILENAME, persistent: false };
  return true;
}

/**
 * Find importScripts("a.js", "b.js") calls in the SW bundle, resolve each path
 * relative to the SW file, and return <script src="..."> tags for the ones that
 * exist on disk (root-relative so they resolve from background.html). The calls
 * themselves are replaced in the SW source with a void 0 no-op so the undefined
 * worker global is never invoked. Paths are resolved against the SW's directory;
 * the emitted src is relative to the extension root (where background.html lives).
 * Returns "" when there are no resolvable importScripts calls.
 */
function hoistImportScripts(dir: string, swPath: string): string {
  const swFile = join(dir, swPath);
  let src: string;
  try {
    src = readFileSync(swFile, "utf-8");
  } catch {
    return "";
  }
  if (!/\bimportScripts\s*\(/.test(src)) return "";

  const swDir = dirname(swPath); // e.g. "service-worker"
  const tags: string[] = [];
  const seen = new Set<string>();
  // Match importScripts( "..."/'...' [, "..."]* ) — string-literal args only
  // (dynamic args can't be statically hoisted; the no-op below still prevents the
  // throw). Each whole call is replaced once neutralized.
  const callRe = /\bimportScripts\s*\(([^)]*)\)/g;
  let neutralized = 0;
  src = src.replace(callRe, (_full, argList: string) => {
    neutralized++;
    const argRe = /["']([^"']+)["']/g;
    let m: RegExpExecArray | null;
    while ((m = argRe.exec(argList))) {
      const rawPath = m[1];
      // Resolve relative to the SW dir → a path from the extension root.
      const fromRoot = join(swDir, rawPath).split("\\").join("/");
      if (seen.has(fromRoot)) continue;
      if (!existsSync(join(dir, fromRoot))) continue; // unresolved → skip the tag; no-op still applies
      seen.add(fromRoot);
      tags.push(`<script src="${fromRoot}"></script>`);
    }
    return "void 0 /* importScripts hoisted to background.html */";
  });

  // Write whenever ANY call was neutralized — even an unresolved target must be
  // de-fanged (it would throw on the undefined global), not just hoisted ones.
  if (neutralized > 0) writeFileSync(swFile, src, "utf-8");
  return tags.length ? tags.join("\n") + "\n" : "";
}
