import { writeFileSync } from "node:fs";
import { join } from "node:path";

export const SHIM_FILENAME = "safari-compat-shim.js";

/**
 * Runtime compatibility shim, prepended to content scripts.
 * Patches the gaps documented in the engineering guide so calls degrade
 * gracefully instead of throwing.
 */
export function shimSource(): string {
  return `// safari-compat-shim.js — auto-generated by chrome2safari. Do not edit.
(function () {
  "use strict";
  var api = typeof browser !== "undefined" ? browser : (typeof chrome !== "undefined" ? chrome : null);
  if (!api) return;

  // storage.sync has no iCloud sync in Safari; route it to local so data persists.
  if (api.storage && api.storage.local) {
    var local = api.storage.local;
    api.storage.sync = {
      get: function () { return local.get.apply(local, arguments); },
      set: function () { return local.set.apply(local, arguments); },
      remove: function () { return local.remove.apply(local, arguments); },
      clear: function () { return local.clear.apply(local, arguments); },
      getBytesInUse: function () {
        return local.getBytesInUse ? local.getBytesInUse.apply(local, arguments) : Promise.resolve(0);
      },
    };
  }

  // sidePanel is absent; fall back to opening the panel HTML in a tab.
  if (typeof chrome !== "undefined" && !chrome.sidePanel && chrome.tabs) {
    chrome.sidePanel = {
      open: function () {
        var url = chrome.runtime.getURL("sidepanel.html");
        return chrome.tabs.create({ url: url });
      },
      setOptions: function () { return Promise.resolve(); },
      getOptions: function () { return Promise.resolve({}); },
      setPanelBehavior: function () { return Promise.resolve(); },
      getPanelBehavior: function () { return Promise.resolve({}); },
    };
  }

  // chrome.identity is unsupported; stub so calls reject instead of crashing.
  // Replace with a hosted OAuth2 redirect flow (see SAFARI_NOTES.md).
  if (typeof chrome !== "undefined" && !chrome.identity) {
    var unsupported = function () {
      return Promise.reject(new Error("chrome.identity is unsupported in Safari. Use a hosted OAuth2 flow."));
    };
    chrome.identity = {
      launchWebAuthFlow: unsupported,
      getAuthToken: unsupported,
      removeCachedAuthToken: function (d, cb) { if (cb) cb(); return Promise.resolve(); },
      getRedirectURL: function () { return ""; },
    };
  }

  // chrome.notifications is missing; degrade to console + best-effort Web Notifications.
  if (typeof chrome !== "undefined" && !chrome.notifications) {
    chrome.notifications = {
      create: function (id, opts, cb) {
        try {
          if (typeof Notification !== "undefined" && Notification.permission === "granted" && opts) {
            new Notification(opts.title || "", { body: opts.message || "", icon: opts.iconUrl });
          }
        } catch (e) { /* ignore */ }
        if (typeof cb === "function") cb(typeof id === "string" ? id : "");
        return Promise.resolve(typeof id === "string" ? id : "");
      },
      clear: function (id, cb) { if (cb) cb(true); return Promise.resolve(true); },
      update: function (id, opts, cb) { if (cb) cb(true); return Promise.resolve(true); },
      getAll: function (cb) { if (cb) cb({}); return Promise.resolve({}); },
    };
  }
})();
`;
}

export function writeShim(targetDir: string): string {
  const p = join(targetDir, SHIM_FILENAME);
  writeFileSync(p, shimSource(), "utf-8");
  return SHIM_FILENAME;
}
